### PR TITLE
3.2.0 style fixes

### PR DESCRIPTION
**Pull request by ahankinson**
This pull request features style fixes for both the Ruby and JavaScript code.

 - Trailing spaces, and spaces on empty lines, have been removed.
 - Tabs have been converted to spaces
 - Some typos in comments have been fixed
 - JSLint has been run on the JavaScript and some of the warnings have been addressed (missing semicolons, triple-equals, implicit global variables, etc.

This pull request is currently up-to-date with 3.2.0-devel. However, I can merge it with other branches and push these changes to this pull request prior to merging into 3.2.0-devel

### CODE REVIEW

**Comment by lpugin** [comment]
@xhero will merge 3.2.0-devel-material into 3.2.0-devel next week. The made in 3.2.0-devel-material are not huge but there will probably be some additional styling issues to fix. Could you merge it into 3.2.0-devel-material? Or do you prefer to wait?

**Comment by ahankinson** [comment]
I just did a preliminary merge with devel-material. I think the proper order should be to wait until @xhero merges his changes in to devel, after which I will do a final merge with this PR and then the style changes on this PR should merge cleanly.

**Comment by lpugin** [comment]
Could you resubmit the PR?

**Comment by ahankinson** [comment]
OK, I think it should be good to go now.

**Comment by lpugin** [comment]
OK, it looks good to me, but I will leave @xhero double check and press the button

**Comment by xhero** [comment]
I have spotted (after merging, unfortunately) a file where a random block of code is deleted:
app/assets/javascripts/tag_header_events.js

is there a reason for this? This change breaks the code.

**Comment by ahankinson** [comment]
Nope, no code should have been deleted. If you point me to the exact block of code is, I'll merge it in the PR and fix it.

**Comment by lpugin** [comment]
It is the lines 161 to 163 just above @xhero 's comment. It would be good to understand how or where this happen just to make sure everything is fine.

**Comment by lpugin** [comment]
Ok, we should post-pone this to version 3.3.0 once we have 3.2.0 release. We should also have distinct PR for ruby and javascript code (at least). The ruby one should be no problem.

**Pull request closed without merging**
