### PR TITLE
Allow $b in institution authority records

### PR DESCRIPTION
**Pull request by fjorba**
710 $b is already allowed in Muscat sources and holdings, but it is not
defined in institutional authority records.  Add it as optional.  Change
also $a to be required and not repeteable in 110, 410 and 510, if the tag is
defined.

### CODE REVIEW

**Comment by xhero** [comment]
I need to ask my colleagues in ZR about this: @HirschSt @jenniferward would it work for us?

**Comment by jenniferward** [comment]
It's fine with me, but maybe Guido can confirm?

**Comment by Docudoctor** [comment]
I confirm. 
Guido

**Comment by xhero** [comment]
Super! Thanks to everybody, I will merge this.

**Pull request merged**
